window:
  padding:
    x: 10
    y: 10
  decorations: none
shell:
  program: /bin/zsh
alt_send_esc: false
colors:
  name: Pastel White
  author: Muzieca
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#000000"
    red: "#db7464"
    green: "#a7e160"
    yellow: "#dbd560"
    blue: "#69b2d6"
    magenta: "#a073d6"
    cyan: "#69e1d3"
    white: "#ffffff"
  bright:
    black: "#88927e"
    red: "#dba08f"
    green: "#bde18b"
    yellow: "#dbda8b"
    blue: "#95a9d6"
    magenta: "#b59fd6"
    cyan: "#95e1d2"
    white: "#c9d0c2"
