window:
  padding:
    x: 10
    y: 10
  decorations: none
shell:
  program: /bin/zsh
# env:
#   TERM: xterm-256color
alt_send_esc: false
# colors:
#  name: Pastel White
#  author: Muzieca
#  primary:
#    background: "#000000"
#    foreground: "#ffffff"
#  cursor:
#    text: "#000000"
#    cursor: "#ffffff"
#  normal:
#    black: "#000000"
#    red: "#db7464"
#    green: "#a7e160"
#    yellow: "#dbd560"
#    blue: "#69b2d6"
#    magenta: "#a073d6"
#    cyan: "#69e1d3"
#    white: "#ffffff"
#  bright:
#    black: "#88927e"
#    red: "#dba08f"
#    green: "#bde18b"
#    yellow: "#dbda8b"
#    blue: "#95a9d6"
#    magenta: "#b59fd6"
#    cyan: "#95e1d2"
#    white: "#c9d0c2"

# onedark
# https://gist.github.com/r-darwish/f8bb21a6c89a02c4bef76cc38bddad39
colors:
  # Default colors
  primary:
    background: '0x000000' # '0x1e2127'
    foreground: '0xabb2bf'

    # Bright and dim foreground colors
    #
    # The dimmed foreground color is calculated automatically if it is not present.
    # If the bright foreground color is not set, or `draw_bold_text_with_bright_colors`
    # is `false`, the normal foreground color will be used.
    #dim_foreground: '0x9a9a9a'
    bright_foreground: '0xe6efff'

  # Cursor colors
  #
  # Colors which should be used to draw the terminal cursor. If these are unset,
  # the cursor color will be the inverse of the cell color.
  #cursor:
  #  text: '0x000000'
  #  cursor: '0xffffff'

  # Normal colors
  normal:
    black:   '0x000000' # '0x1e2127'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0x828791'

  # Bright colors
  bright:
    black:   '0x5c6370'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xe6efff'

  # Dim colors
  #
  # If the dim colors are not set, they will be calculated automatically based
  # on the `normal` colors.
  dim:
    black:   '0x1e2127'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0x828791'

  # Indexed Colors
  #
  # The indexed colors include all colors from 16 to 256.
  # When these are not set, they're filled with sensible defaults.
  #indexed_colors:
  #  - { index: 16, color: '0x000000' }
