#tap 'caskroom/cask'
#tap 'caskroom/fonts'
#tap 'caskroom/versions'
#tap 'homebrew/boneyard'


# Shell
brew 'coreutils'
brew 'zsh'
brew 'ack'
brew 'tldr'
brew 'thefuck'
brew 'ccat'
brew 'htop'
brew 'ncdu'
#brew 'zsh-syntax-highlighting'
# cask 'font-fira-code'
# brew 'antigen'

# General software
#cask 'alfred'
#cask 'amethyst'
#cask 'bettertouchtool'
#cask 'caffeine'
#cask 'dropbox'
#cask 'google-chrome'
#cask 'google-drive-file-stream'
#cask 'macpass'
#cask 'skim'
#cask 'tunnelblick'
#cask 'telegram-desktop'

# Dev
brew 'awscli'
brew 'azure-cli'
brew 'cmake'
brew 'clang-format'
#brew 'docker'
brew 'git'
brew 'nvm'
brew 'pandoc'
brew 'pandoc-citeproc'
brew 'rclone'
brew 'wget'
cask 'mactex'
cask 'visual-studio-code'
cask 'miniconda'
